# settings, per RFC 3561

PACKET_INBOX_SZ = 10
PACKET_OUTBOX_SZ = 10

DATA_QUEUE_TIMEOUT = 240 # seconds

# timeouts + limits
ACTIVE_ROUTE_TIMEOUT = 60 # seconds
INACTIVE_ROUTE_TIMEOUT = 90
ALLOWED_HELLO_LOSS   = 2
# DELETE_PERIOD = 
# MIN_REPAIR_TTL = 
HELLO_INTERVAL       = 1 # s
ACK_INTERVAL         = 2 # s
LOCAL_ADD_TTL        = 2
NET_DIAMETER         = 35
NODE_TRAVERSAL_TIME  = 1   # s
RREQ_RATELIMIT       = 10   # max broadcastable rreqs per second
RREQ_RETRIES         = 2    # max retries
RERR_RATELIMIT       = 10
TIMEOUT_BUFFER       = 2
TTL_START            = 1
TTL_INCREMENT        = 2
TTL_THRESHOLD        = 7
# TTL_VALUE = 

# NET_TRAVERSAL_TIME   = 2 * NODE_TRAVERSAL_TIME * NET_DIAMETER # ms
NET_TRAVERSAL_TIME   = int(0.2 * NODE_TRAVERSAL_TIME * NET_DIAMETER) # ms
BLACKLIST_TIMEOUT    = RREQ_RETRIES * NET_TRAVERSAL_TIME      # ms
MAX_REPAIR_TTL       = 0.3 * NET_DIAMETER
MY_ROUTE_TIMEOUT     = 2 * ACTIVE_ROUTE_TIMEOUT               # ms
NEXT_HOP_WAIT        = NODE_TRAVERSAL_TIME + 10
PATH_DISCOVERY_TIME  = 2 * NET_TRAVERSAL_TIME # ms to buffer rreq after sending, to prevent loops
RING_TRAVERSL_TIME   = 2 * NODE_TRAVERSAL_TIME
HELLO_LIFETIME        = ALLOWED_HELLO_LOSS * HELLO_INTERVAL

PATH_DISCOVERY_INCREMENT = 1
LIFETIME_INCREMENT = 1
MAX_RECENT_RREQS = 5

NEIGHBOR_MAX_REPAIRS = 2
PASSIVE_ACK_TIMEOUT = 5